# -*- coding: utf-8 -*-
# Author : Peter Wu

{
    'name': "ERA 租屋住戶管理模組",
    'version': '13.0',
    'summary': "ERA 租屋住戶管理模組",
    'description': """ERA 租屋住戶管理模組(住戶日用電度數記錄/租戶儲值收款記錄/費用對帳記錄Line租戶)""",
    'author': "LANSIR Technology CO.,LTD.",
    'category': 'HouseHold Manager',
    'depends': [],
    'data': [ 'data/era_payment_item.xml',
               'data/era_payment_month.xml',
               # 'data/era_emeterhub_data.xml',
              'security/era_security.xml',
              'security/era_security1.xml',
              'security/line_notify_group.xml',
              'security/ir.model.access.csv',
              'security/era_maintenance_security.xml',
              'views/era_household_member.xml',
              'views/era_household_house.xml',
              'views/era_household_line.xml',
              'wizards/conn_mysql_wizard.xml',
              'views/line_notify_configure.xml',
              # 'wizards/line_notify_send.xml',
              'views/era_household_config.xml',
              'views/era_household_bill_line.xml',
              'views/era_household_bill_line_his.xml',
              'wizards/line_notify_send.xml',
              'wizards/mon_amount_report_wizard.xml',
               'reports/era_bill_templates.xml',
              'reports/mmonth_template.xml',
              'reports/era_bill_reports.xml',
              'wizards/era_household_payment.xml',
              'wizards/era_month_report_wizard.xml',
              'views/era_household_maintenance.xml',
              'wizards/era_maintennance_report_wizard.xml',
              'reports/maintenance_template.xml',
              'wizards/era_start_scale_wizard.xml',
              'wizards/era_member_line_wizard.xml',
              'wizards/era_household_previous_balance_wizard.xml',
              'wizards/era_household_mixsearch.xml',
              'views/era_emeter_mixsearch_line.xml',
              'views/era_excel_download.xml',
              'views/era_member_payment.xml',
              'wizards/era_contract_wizard.xml',
              'views/era_emeterhub.xml',
              'wizards/era_memberout_wizard.xml',
              'wizards/era_escaletot_wizard.xml',
              'wizards/era_memberin_wizard.xml',
              'views/era_house_member_chk.xml',
              'wizards/era_housemember_chk_wizard.xml',
              'wizards/era_archive_delete.xml',
              'views/era_menu.xml',
              ],
    'installable': True,
    'application': True,

}
