# -*- coding: utf-8 -*-
# Author : Peter Wu


{
    'name': u"<1>.LANSIR For 精宏IOT 工單模組",
    'version': '1.0',
    'summary': "LANSIR For 精宏IOT 工單模組",

    'description': """LANSIR For 精宏IOT 工單模組.... """,
    'author': "LANSIR Technology,Peter Wu",
    'category': 'Work Order',
    'depends': ['purchase','sale','product','stock', 'maintenance','sh_message','hr'],
    'data': [
              'data/gh_iot_serverinfo.xml',
              'data/gh_iot_sequence.xml',
              'data/gh_iot_maintenance_status.xml',
              'data/gh_iot_serviceprod.xml',
              'data/gh_iot_proofing_data.xml',
              'data/gh_fish_report_data.xml',
              'security/gh_iot_security.xml',
              'security/ir.model.access.csv',
              # 'security/gh_iot_rule.xml',
              'data/gh_iot_measure_tool.xml',
              'wizards/iot_restart_wizard.xml',
              'views/gh_iot_measure_tool.xml',
              'views/gh_maintenance_inherit.xml',
              'views/gh_product_template_inherit.xml',
              'wizards/iot_init_pickle_wizard.xml',
              'views/gh_iot_server.xml',
              'views/gh_iot_employee.xml',
              'views/gh_iot_workorder.xml',
              'report/wkorder_select_item.xml',
              'wizards/gh_iot_open_workorder.xml',
              'wizards/gh_iot_wkorderreport_wizard.xml',
               'report/alldo_gh_iot_wkorder_report1.xml',
              'report/alldo_gh_iot_report.xml',
              'report/alldo_gh_iot_wkorder_report.xml',
              'wizards/iot_mo_start_wizard.xml',
              'wizards/iot_mo_action_wizard.xml',
              'views/gh_iot_po_wkorder.xml',
              'wizards/iot_shutdown_wizard.xml',
              'wizards/gh_iot_po_stockin.xml',
              'views/gh_iot_respartner_inherit.xml',
              'views/gh_iot_outsuborder.xml',
              'wizards/gh_outsourcing_out_wizard.xml',
              'wizards/gh_outsourcing_in_wizard.xml',
              'wizards/gh_iot_blank_stockin.xml',
              'report/alldo_gh_iot_empbarcode_report.xml',
              'wizards/gh_iot_empbarcode_wizard.xml',
              'views/gh_iot_empinfo.xml',
              'views/gh_iot_main_status.xml',
              'views/gh_maintenance_inherit1.xml',
              'views/gh_iot_equipstatusinfo.xml',
              'wizards/gh_iot_equipstatus_barcode_wizard.xml',
              'report/alldo_gh_iot_equipstatusbarcode_report.xml',
              'views/gh_iot_saleorder.xml',
              'views/res_partner_inherit.xml',
              'wizards/gh_iot_mo_add.xml',
              'wizards/gh_iot_shipping_report_wizard.xml',
              'views/stock_picking_inherit.xml',
              'views/gh_iot_shipping_report.xml',
              'report/alldo_gh_iot_shipping_report.xml',
              'views/gh_iot_ngreturn_report.xml',
              'wizards/gh_iot_ngreturn_report_wizard.xml',
              'report/alldo_gh_iot_ngreturn_report.xml',
              'wizards/gh_iot_outsourcing_report_wizard.xml',
              'views/gh_iot_outsourcing_report.xml',
              'report/alldo_gh_iot_outsourcing_report.xml',
              'wizards/gh_iot_dbclear_wizard.xml',
              'views/gh_iot_excel_download.xml',
              'wizards/emp_attendance_export_wizard.xml',
              'wizards/outsourcing_inout_wizard.xml',
              'wizards/gh_iot_shipping_excel_wizard.xml',
              'wizards/gh_iot_deployment_wizard.xml',
              'wizards/gh_iot_workorder_performance_wizard.xml',
              'wizards/gh_iot_replaceline_wizard.xml',
              'wizards/gh_iot_blank_moin.xml',
              'wizards/gh_iot_mixsearch.xml',
              'views/gh_iot_workorder_performance.xml',
              'views/gh_iot_replaceline_list.xml',
              'wizards/gh_iot_mixsearch_replaceline.xml',
              'views/gh_iot_prodstock.xml',
              'views/gh_iot_company_stockloc.xml',
              'wizards/gh_iot_prodstock_wizard.xml',
              'report/wkorder_select_item1.xml',
              'pivots/gh_iot_performance_pivot.xml',
              'wizards/gh_iot_ngreturn_excel_wizard.xml',
              'views/gh_iot_ngreturn_selectitem.xml',
              'views/gh_iot_bells.xml',
              'views/gh_iot_processing_view.xml',
              'wizards/gh_iot_wkorder_processing_wizard.xml',
              'views/gh_iot_manperformance.xml',
              'views/gh_iot_equipperformance.xml',
              'views/gh_iot_stockmove_list.xml',
              'wizards/gh_iot_stockmove_mixsearch.xml',
              'wizards/gh_iot_blank_shipping.xml',
              'views/gh_iot_restartsetting.xml',
              'views/gh_prod_goodng_list.xml',
              'wizards/gh_iot_dai_wizard.xml',
              'wizards/gh_booking_release_wizard.xml',
              'views/gh_iot_booking.xml',
              'wizards/gh_booking_wizard.xml',
              'wizards/gh_po_wkordert_wizard.xml',
              'wizards/gh_iot_prod_moin.xml',
              'wizards/gh_prodout_in_wizard.xml',
              'wizards/gh_package_mo_wizard.xml',
              # 'views/purchase_order_inherit.xml',
              'views/gh_iot_workorder_inherit.xml',
              # 'views/gh_iot_po_wkorder_inherit.xml',
              'views/gh_iot_po_wkorder_list.xml',
              'wizards/ghiot_powkorder_list_wizard.xml',
              'views/res_partner_inherit1.xml',
              # 'wizards/conn_mysql_wizard.xml',
              'wizards/gh_iot_semiprod_moin.xml',
              'wizards/gh_semiprodout_in_wizard.xml',
              'views/stock_picking_inherit1.xml',
              'views/purchase_order_inherit1.xml',
              'report/purchase_order_templates.xml',
              'report/purchase_order_templates1.xml',
              'report/alldo_gh_fish_report.xml',
              'views/purchase_order_inherit2.xml',
              'wizards/emp_attendance_firstwork_export_wizard.xml',
              'views/gh_iot_equipperformance2.xml',
              'wizards/gh_iot_open_stockout.xml',
              'wizards/gh_iot_mintime_search.xml',
              'views/gh_iot_mintime_list.xml',
              'views/gh_iot_stock_change.xml',
              'views/alldo_gh_iot_supplierinfo.xml',
              'wizards/gh_supplierinfo_wizard.xml',
              'views/purchase_last10_list.xml',
              'wizards/purchase_last10_wizard.xml',
              'views/gh_proofing.xml',
              'views/gh_iot_cus_stocklist.xml',
              'wizards/ghiot_cus_stocklist_wizard.xml',
              'wizards/gh_iot_piprodsearch.xml',
              'report/ghiot_pi_prod_analysis.xml',
              'views/gh_iot_menu.xml',
    ],
    'installable': True,
    'application': True,

}
