# -*- coding: utf-8 -*-
# Author : Peter Wu
{
    'name': "CloudRent 租屋包租代管模組",
    'version': '13.0',
    'summary': "CloudRent 租屋包租代管模組",
    'description': """CloudRent 租屋包租代管模組""",
    'author': "ALLDO Technology CO.,LTD.",
    'category': 'CloudRet Escrow Maagemet',
    'depends': ['crm','sales_team'],
    'data': ['security/cloudrent_security.xml',
             'security/ir.model.access.csv',
             'data/cloudrent_grant_data.xml',
             'data/cloudrent_grant_value_data.xml',
             'data/cloudrent_crm_stage.xml',
             'data/cloudrent_report_data.xml',
             'data/cloudrent_equip_part.xml',
             'data/cloudrent_docfilename_data.xml',
             'data/cloudrent_contract_data.xml',
             'data/cloudrent_irconfig_parameter.xml',
             'views/cloudrent_escrow.xml',
             'views/cloudrent_escrow_member.xml',
             'views/cloudrent_grant_item.xml',
             'views/cloudrent_grant_fee.xml',
             'views/cloudrent_contract_match.xml',
             'views/crm_lead_form_inherit.xml',
             'views/crm_lead1_form_inherit.xml',
             'views/res_users_inherit.xml',
             'views/cloudrent_build.xml',
             'views/cloudrent_escrow_lessor.xml',
             'views/cloudrent_escrow_lessee.xml',
             'wizards/cloudrent_month_report.xml',
             'wizards/cloudrent_week_report.xml',
             'views/cloudrent_week_download.xml',
             'views/cloudrent_month_download.xml',
             'views/cloudrent_entrust_escrow_contract.xml',
             'views/cloudrent_entrust_management_contract.xml',
             'views/cloudrent_applyfor_grantee.xml',
             # 'report/cloudrent_report.xml',
             'wizards/cloudrent_agent_grant_fee.xml',
             'views/cloudrent_applyfor_escrow1.xml',
             'views/cloudrent_applyfor_escrow2.xml',
             'views/cloudrent_applyfor_escrow3.xml',
             'views/cloudrent_applyfor_escrow4.xml',
             'views/cloudrent_situation_sitecheck.xml',
             'wizards/cloudrent_match_import.xml',
             'views/cloudrent_visit_calendar.xml',
             'views/cloudrent_agent_visit_service.xml',
             'views/cloudrent_equip_part.xml',
             'views/cloudrent_quit_lease.xml',
             'views/cloudrent_quit_equip_part_form.xml',
             'views/cloudent_docfilename.xml',
             'views/cloudrent_contract_version.xml',
             'views/cloudrent_contract_data.xml',
             'views/cloudrent_lessee_sitecheck.xml',
             'wizards/cloudrent_renew_match.xml',
             'views/cloudrent_sale_calendar.xml',
             'views/cloudrent_secretary_calendar.xml',
             'views/cloudrent_sale_calendar_tag.xml',
             'views/cloudrent_visit_calendar_tag.xml',
             'views/cloudrent_escrow_sale.xml',
             'views/cloudrent_escrow_manager.xml',
             'views/cloudrent_escrow_assetagent.xml',
             'views/cloudrent_escrow_vendor.xml',
             'views/cloudrent_escrow_secretary.xml',
             'views/cloudrent_repair_calendar_tag.xml',
             'views/cloudrent_repair_calendar.xml',
             'views/cloudrent_vendor_repair_service.xml',
             'views/cloudrent_menu.xml',

              ],
    'installable': True,
    'application': True,

}
