# -*- coding: utf-8 -*-
# Author: Peter Wu


{
    'name': u'<2>.NEWEB 申購/採購管理模組',
    'license': 'LGPL-3',
    'version': '13.0',
    'category': 'Project management',
    'sequence': 3,
    "website": "http://www.lansir.com.tw",
    "author": "LANSIR Technology",
    'depends': ['base', 'sale','neweb_project','purchase','hr'],
    'data': ['security/ir.model.access.csv',
             'views/neweb_require_purchase.xml',
             'data/neweb_RFQ_flow_message.xml',
             'data/neweb_require_data.xml',
             'wizards/neweb_unpurchase_item_wizard.xml',
             'wizards/neweb_unpur_item_select.xml',
             'wizards/neweb_unproj_item_select.xml',
             'wizards/neweb_unproj_item_wizard.xml',
             'views/neweb_purchase_inherit.xml',
             'views/neweb_mabackup_config.xml',
             'views/neweb_maparts_config.xml',
            'views/neweb_purchase_manager.xml',
             'views/neweb_purchase_categ.xml',
             'security/neweb_purchase_menu_security.xml',
             'security/neweb_require_security.xml',
             'data/neweb_RFQ_wkf_approve_mail.xml',
             'data/neweb_RFQ_wkf_reject_mail.xml',
             'data/neweb_purchase_approve_mail.xml',
             'data/neweb_purchase_reject_mail.xml',
             'views/neweb_purchase_inherit1.xml',
             'views/neweb_purchase_inherit2.xml',
             'views/neweb_purchase_search_inherit.xml',
             'views/neweb_purchase_inherit4.xml',
             'views/neweb_purchase_inherit5.xml',
             'views/neweb_purchase_inherit6.xml',
             'views/neweb_purchase_inherit7.xml',
             'wizards/neweb_reget_partner_wizard.xml',
             'wizards/neweb_prod_price_analysis_wizard.xml',
             'views/neweb_prod_price_list.xml',
             'views/neweb_rps_schedule.xml',
             'wizards/neweb_rps_wizard.xml',
             'views/neweb_rps_download.xml',
             ],
    'application': True,
    'installable': True,
    'description': u'<2>.NEWEB 申購/採購管理模組',
    'summary': u'<2>.NEWEB 申購/採購管理模組',
}
