# -*- coding: utf-8 -*-
# Author : Peter Wu

{
    'name': u"<14>.NEWEB Build Fish報表",
    'version': '1.0',
    'summary': "NEWEB build fish Report Template",
    'sequence': 16,
    'description': """NEWEB Build Fish Report Template.... """,
    'author': "ALLDO Technology,Peter Wu",
    'category': 'Reports',
    'depends': ['report_extend_bf','report_extend_bf_barcode','neweb_project','neweb_sale_analysis','neweb_repair','neweb_emp_timesheet'],
    'data': [ 'data/bf_data.xml',
              'security/ir.model.access.csv',
             'report/sale_order_report.xml',
             # 'report/sale_order_print_btn.xml',
             'report/neweb_project_report.xml',
             # 'report/neweb_project_print_btn.xml',
             'report/neweb_expense_report.xml',
             # 'report/neweb_expense_btn.xml',
             'report/neweb_travel_report.xml',
             # 'report/neweb_travel_btn.xml',
             'report/neweb_require_purchase_report.xml',
             # 'report/neweb_require_purchase_btn.xml',
             'report/neweb_repair_report.xml',
             # 'report/neweb_repair_btn.xml',
             # 'report/neweb_purchase_btn.xml',
             'report/neweb_purchase_report.xml',
             'report/neweb_shipping_report.xml',
             'report/neweb_stockin_report.xml',
             'report/neweb_invoiceopen_report.xml',
             # 'report/neweb_invoiceopen_btn.xml',
             # 'report/neweb_shipping_btn.xml',
             # 'report/neweb_stockin_btn.xml',
             'report/neweb_assign_custom_report.xml',
             'report/neweb_assign_custom_btn.xml',
             'report/neweb_eng_assign_report.xml',
             'report/neweb_eng_assign_btn.xml',
             'report/neweb_official_doc_report.xml',
             # 'report/neweb_official_doc_btn.xml',
              'report/neweb_purinv_report.xml',
              'report/neweb_custom_data_report.xml',
              # 'report/neweb_purinv_btn.xml',


    ],
    'installable': True,
    'application': True,

}
