# -*- coding: utf-8 -*-
# Author : Peter Wu


{
    'name': u"<1>.LANSIR For ipla IOT模組",
    'version': '1.0',
    'summary': "LANSIR For ipla IOT模組",

    'description': """LANSIR For IPLA IOT模組.... """,
    'author': "LANSIR Technology,Peter Wu",
    'category': 'Work Order',
    'depends': ['purchase','sale','product','stock', 'maintenance','sh_message','hr','mrp'],
    'data': [
             'data/ipla_iot_sequence.xml',
             'data/ipla_iot_serverinfo.xml',
             'data/ipla_iot_maintenance_status.xml',
             'data/ipla_iot_furance.xml',
              'security/ipla_iot_security.xml',
             'security/ir.model.access.csv',
             'views/ipla_maintenance_inherit.xml',
             'views/ipla_maintenance_inherit1.xml',
             'views/ipla_iot_respartner_inherit.xml',
             'views/res_partner_inherit.xml',
             'views/ipla_product_template_inherit.xml',
             'views/ipla_iot_respartner_inherit.xml',
             'views/ipla_iot_empinfo.xml',
             'views/ipla_iot_excel_download.xml',
             'views/ipla_iot_measure_tool.xml',
             'views/ipla_iot_saleorder.xml',
             'views/ipla_iot_server.xml',
             'views/ipla_iot_equipstatusinfo.xml',
             'views/ipla_iot_main_status.xml',
             'views/stock_picking_inherit.xml',
             'views/ipla_iot_ngreturn_report.xml',
             'views/ipla_iot_outsourcing_report.xml',
             'views/ipla_iot_outsuborder.xml',
             'views/ipla_iot_po_wkorder.xml',
             'views/ipla_iot_shipping_report.xml',
             'views/ipla_mrp_production_inhert.xml',
             'views/ipla_iot_workorder.xml',
             'reports/alldo_ipla_iot_empbarcode_report.xml',
             'reports/alldo_ipla_iot_equipstatusbarcode_report.xml',
             'reports/alldo_ipla_iot_ngreturn_report.xml',
             'reports/alldo_ipla_iot_outsourcing_report.xml',
             'reports/alldo_ipla_iot_outsourcing_report1.xml',
             'reports/alldo_ipla_iot_shipping_report.xml',
             'reports/alldo_ipla_iot_wkorder_report.xml',
             'reports/wkorder_select_item.xml',
             'reports/alldo_ipla_iot_report.xml',
             'wizards/ipla_iot_blank_stockin.xml',
             'wizards/ipla_iot_dbclear_wizard.xml',
             'wizards/ipla_iot_empbarcode_wizard.xml',
             'wizards/ipla_iot_equipstatus_barcode_wizard.xml',
             'wizards/ipla_iot_mo_add.xml',
             'wizards/ipla_iot_ngreturn_report_wizard.xml',
             'wizards/ipla_iot_open_workorder.xml',
             'wizards/ipla_iot_outsourcing_report_wizard.xml',
             'wizards/ipla_iot_po_stockin.xml',
             'wizards/ipla_iot_shipping_excel_wizard.xml',
             'wizards/ipla_iot_shipping_report_wizard.xml',
             'wizards/ipla_iot_wkorderreport_wizard.xml',
             'wizards/ipla_outsourcing_in_wizard.xml',
             'wizards/ipla_outsourcing_out_wizard.xml',
             'wizards/emp_attendance_export_wizard.xml',
             'wizards/iot_init_pickle_wizard.xml',
             'wizards/iot_mo_action_wizard.xml',
             'wizards/iot_mo_start_wizard.xml',
             'wizards/iot_restart_wizard.xml',
             'wizards/iot_shutdown_wizard.xml',
             'wizards/outsourcing_inout_wizard.xml',
             'views/ipla_mold.xml',
             'views/ipla_iot_employee.xml',
             'views/ipla_iot_workorder_performance.xml',
             'views/ipla_iot_replaceline_list.xml',
             'views/ipla_iot_prodstock.xml',
             'views/ipla_iot_company_stockloc.xml',
             'views/ipla_casting_furnace.xml',
             'wizards/ipla_iot_mixsearch.xml',
             'wizards/ipla_iot_mixsearch_replaceline.xml',
             'wizards/ipla_iot_prodstock_wizard.xml',
             'wizards/ipla_furnace_move.xml',
             'import_wizards/partner_import_wizard.xml',
             'import_wizards/prod_import_wizard.xml',
             'import_wizards/mold_import_wizard.xml',
             'wizards/ipla_out_to_out_wizard.xml',
             'views/ipla_electronic_scale.xml',
             'views/sale_order_inherit.xml',
             'views/purchase_order_inherit.xml',
             'views/ipla_stock_quant_inherit.xml',
             'wizards/ipla_material_to_prod_wizard.xml',
              'views/ipla_iot_furance_report.xml',
              'wizards/ipla_iot_furance_report_wizard.xml',
              'reports/alldo_ipla_iot_furance_report.xml',
              'reports/alldo_ipla_iot_newmaterial_report.xml',
              'reports/alldo_ipla_iot_recyclematerial_report.xml',
              'views/ipla_mold_report.xml',
              'wizards/ipla_iot_mold_report_wizard.xml',
              'reports/alldo_ipla_iot_mold_report.xml',
              'views/ipla_stock_quant_report.xml',
              'reports/alldo_ipla_iot_quant_report.xml',
               'wizards/ipla_iot_quant_report_wizard.xml',
              'views/ipla_mrp_bom_inherit.xml',
              'import_wizards/packaging_import_wizard.xml',
              'wizards/gen_bom_wizard.xml',
              'views/ipla_mrp_production_inherit1.xml',
              'wizards/ipla_iot_ngreturn_excel_wizard.xml',
              'views/ipla_account_move_inherit.xml',
              'wizards/ipla_account_move_wizard.xml',
              'views/ipla_account_move_selectitem.xml',
              'reports/alldo_ipla_iot_accountmove_report.xml',
              'reports/alldo_ipla_iot_scale_mode_list.xml',
              'wizards/ipla_mixsearch_scale_move.xml',
              'views/ipla_mixsearch_saclemove.xml',
              'reports/alldo_ipla_iot_barcode1_report.xml',
              'reports/alldo_ipla_iot_barcode2a_report.xml',
              'reports/alldo_ipla_iot_barcode2b_report.xml',
              'reports/alldo_ipla_iot_barcode34_report.xml',
              'reports/alldo_ipla_iot_barcode5_report.xml',
              'wizards/ipla_qc_ng_wizard.xml',
              'views/ipla_iot_restartsetting.xml',
              'views/ipla_iot_manperformance.xml',
              'views/ipla_iot_equipperformance.xml',
              'pivots/ipla_iot_performance_pivot.xml',
              'views/ipla_prod_goodng_list.xml',
              'views/ipla_iot_menu.xml',
    ],
    'installable': True,
    'application': True,

}
