# -*- coding: utf-8 -*-
{
	'name': u'<7>.NEWEB 工時管理模組',
	'version': '13.0',
	'summary': "Employee Timesheet Management",
	'sequence': 10,
	'description': """
Neweb Contract
==============
Employee Timesheet management Module for Neweb.""",
    "website": "http://www.odootw.com.tw",
    "author": "AllDo Technology",
    'category': 'Uncategorized',
    'version': '10',
    'depends': ['base', 'neweb_base','calendar','neweb_repair','neweb_contract','sh_message'],
    'data': [
             'security/neweb_emp_timesheet_security.xml',
             'security/neweb_emp_timesheet_rule_security.xml',
             'security/neweb_emp_timesheetline_rule_security.xml',
             'security/neweb_todo_rule_security.xml',
             'security/neweb_inspection_rule_security.xml',
             'security/neweb_repair_rule_security.xml',
             'security/neweb_timesheet_download_security.xml',
             'security/neweb_timesheet_pivot_security.xml',
             'security/ir.model.access.csv',
             'views/neweb_timesheet_worktype.xml',
             'views/neweb_timesheet_input.xml',
             'views/neweb_timesheet_calendar.xml',
             'views/neweb_emp_timesheet_cost.xml',
             'views/neweb_inspection_line_inherit.xml',
             'views/neweb_repair_work_log_inherit.xml',
             'data/neweb_timesheet_lockdata.xml',
             'data/neweb_worktype_data.xml',
             'data/neweb_inspection_alert_mail.xml',
             'data/neweb_tolerance_data.xml',
             'views/neweb_timesheet_lock.xml',
             'views/neweb_assign_inherit.xml',
             'wizards/neweb_import_timesheet.xml',
             'views/neweb_inspection_calendar.xml',
             'views/neweb_repair_calendar.xml',
             'views/neweb_todo_calendar.xml',
             'views/neweb_hrholiday.xml',
             'reports/timesheet_pivot.xml',
             'reports/timesheet_expcost_pivot.xml',
             'views/neweb_tolerance_setting.xml',
             'wizards/timesheet_nocomplete_wizard.xml',
             'views/neweb_timesheet_download.xml',
             'wizards/timesheet_record_wizard.xml',
             'wizards/neweb_update_contract_type_wizard.xml',
             'views/neweb_timesheet_adjustowner.xml',
             'wizards/neweb_change_emp_wizard.xml',
             'views/neweb_emp_timesheet_menu.xml',
             'views/neweb_repair_inherit.xml',

    ],

    'description' : '<7>.NEWEB 工時管理模組',
    'summary': '<7>.NEWEB 工時管理模組',
    'installable': True,
    'application': True,

}
