# -*- coding: utf-8 -*-
# Author : Peter Wu


{
    'name': u"<1>.LANSIR For ACME IOT模組",
    'version': '1.0',
    'summary': "LANSIR For ACME IOT模組",

    'description': """LANSIR For ACME IOT模組.... """,
    'author': "LANSIR Technology,Peter Wu",
    'category': 'Work Order',
    'depends': ['purchase','sale','product','stock', 'maintenance','sh_message','hr','mrp'],
    'data': [
             'data/acme_iot_sequence.xml',
             'data/acme_iot_serverinfo.xml',
             'data/acme_iot_maintenance_status.xml',
             'data/acme_iot_furance.xml',
              'security/acme_iot_security.xml',
             'security/ir.model.access.csv',
             'views/acme_maintenance_inherit.xml',
             'views/acme_maintenance_inherit1.xml',
             'views/acme_iot_respartner_inherit.xml',
             'views/res_partner_inherit.xml',
             'views/acme_product_template_inherit.xml',
             'views/acme_iot_respartner_inherit.xml',
             'views/acme_iot_empinfo.xml',
             'views/acme_iot_excel_download.xml',
             'views/acme_iot_measure_tool.xml',
             'views/acme_iot_saleorder.xml',
             'views/acme_iot_server.xml',
             'views/acme_iot_equipstatusinfo.xml',
             'views/acme_iot_main_status.xml',
             'views/stock_picking_inherit.xml',
             'views/acme_iot_ngreturn_report.xml',
             'views/acme_iot_outsourcing_report.xml',
             'views/acme_iot_outsuborder.xml',
             'views/acme_iot_po_wkorder.xml',
             'views/acme_iot_shipping_report.xml',
             'views/acme_mrp_production_inhert.xml',
             'views/acme_iot_workorder.xml',
             'reports/alldo_acme_iot_empbarcode_report.xml',
             'reports/alldo_acme_iot_equipstatusbarcode_report.xml',
             'reports/alldo_acme_iot_ngreturn_report.xml',
             'reports/alldo_acme_iot_outsourcing_report.xml',
             'reports/alldo_acme_iot_outsourcing_report1.xml',
             'reports/alldo_acme_iot_outsourcing_report2.xml',
             'reports/alldo_acme_iot_shipping_report.xml',
             'reports/alldo_acme_iot_shipping_report1.xml',
             'reports/alldo_acme_iot_wkorder_report.xml',
             'reports/wkorder_select_item.xml',
             'reports/alldo_acme_iot_report.xml',
             'wizards/acme_iot_blank_stockin.xml',
             'wizards/acme_iot_dbclear_wizard.xml',
             'wizards/acme_iot_empbarcode_wizard.xml',
             'wizards/acme_iot_equipstatus_barcode_wizard.xml',
             'wizards/acme_iot_mo_add.xml',
             'wizards/acme_iot_ngreturn_report_wizard.xml',
             'wizards/acme_iot_open_workorder.xml',
             'wizards/acme_iot_outsourcing_report_wizard.xml',
             'wizards/acme_iot_po_stockin.xml',
             'wizards/acme_iot_shipping_excel_wizard.xml',
             'wizards/acme_iot_shipping_report_wizard.xml',
             'wizards/acme_iot_wkorderreport_wizard.xml',
             'wizards/acme_outsourcing_in_wizard.xml',
             'wizards/acme_outsourcing_out_wizard.xml',
             'wizards/emp_attendance_export_wizard.xml',
             'wizards/iot_init_pickle_wizard.xml',
             'wizards/iot_mo_action_wizard.xml',
             'wizards/iot_mo_start_wizard.xml',
             'wizards/iot_restart_wizard.xml',
             'wizards/iot_shutdown_wizard.xml',
             'wizards/outsourcing_inout_wizard.xml',
             'views/acme_mold.xml',
             'views/acme_iot_employee.xml',
             'views/acme_iot_workorder_performance.xml',
             'views/acme_iot_replaceline_list.xml',
             'views/acme_iot_prodstock.xml',
             'views/acme_iot_company_stockloc.xml',
             'views/acme_casting_furnace.xml',
             'wizards/acme_iot_mixsearch.xml',
             'wizards/acme_iot_mixsearch_replaceline.xml',
             'wizards/acme_iot_prodstock_wizard.xml',
             'wizards/acme_furnace_move.xml',
             'import_wizards/partner_import_wizard.xml',
             'import_wizards/prod_import_wizard.xml',
             'import_wizards/mold_import_wizard.xml',
             'wizards/acme_out_to_out_wizard.xml',
             'views/acme_electronic_scale.xml',
             'views/sale_order_inherit.xml',
             'views/purchase_order_inherit.xml',
             'views/acme_stock_quant_inherit.xml',
             'wizards/acme_material_to_prod_wizard.xml',
              'views/acme_iot_furance_report.xml',
              'wizards/acme_iot_furance_report_wizard.xml',
              'reports/alldo_acme_iot_furance_report.xml',
              'reports/alldo_acme_iot_newmaterial_report.xml',
              'reports/alldo_acme_iot_recyclematerial_report.xml',
              'views/acme_mold_report.xml',
              'wizards/acme_iot_mold_report_wizard.xml',
              'reports/alldo_acme_iot_mold_report.xml',
              'views/acme_stock_quant_report.xml',
              'reports/alldo_acme_iot_quant_report.xml',
               'wizards/acme_iot_quant_report_wizard.xml',
              'views/acme_mrp_bom_inherit.xml',
              'import_wizards/packaging_import_wizard.xml',
              'wizards/gen_bom_wizard.xml',
              'views/acme_mrp_production_inherit1.xml',
              'wizards/acme_iot_ngreturn_excel_wizard.xml',
              'views/acme_account_move_inherit.xml',
              'wizards/acme_account_move_wizard.xml',
              'views/acme_account_move_selectitem.xml',
              'reports/alldo_acme_iot_accountmove_report.xml',
              'reports/alldo_acme_iot_scale_mode_list.xml',
              'wizards/acme_mixsearch_scale_move.xml',
              'views/acme_mixsearch_saclemove.xml',
              'reports/alldo_acme_iot_barcode1_report.xml',
              'reports/alldo_acme_iot_barcode2a_report.xml',
              'reports/alldo_acme_iot_barcode2b_report.xml',
              'reports/alldo_acme_iot_barcode34_report.xml',
              'reports/alldo_acme_iot_barcode5_report.xml',
              'wizards/acme_qc_ng_wizard.xml',
              'views/acme_iot_restartsetting.xml',
              'views/acme_iot_manperformance.xml',
              'views/acme_iot_equipperformance.xml',
              'pivots/acme_iot_performance_pivot.xml',
              'views/acme_prod_goodng_list.xml',
              'views/acme_prodout.xml',
              'reports/alldo_acme_iot_prodout_report.xml',
              'views/acme_scalegroup_setting.xml',
              'pivots/acme_iot_dayscale_pivot.xml',
              'wizards/acme_quant_release_wizard.xml',
              'views/acme_iot_quant_release.xml',
              'wizards/acme_daylast_wizard.xml',
              'views/acme_iot_stockmove_list.xml',
              'wizards/acme_iot_stockmove_mixsearch.xml',
              'views/acme_iot_shipping_report1.xml',
              'reports/alldo_acme_iot_shipping_report1.xml',
              'wizards/acme_mattoblank_wizard.xml',
              'views/acme_purchase_inherit.xml',
              'views/acme_iot_accmove_excel_download.xml',
              'wizards/accmove_export_wizard.xml',
              'views/acme_prodout_inherit.xml',
              'views/acme_iot_outsuborder_inherit.xml',
              'wizards/acme_kpi_wizard.xml',
              'views/acme_iot_outkpi.xml',
              'views/acme_iot_workorder_inherit.xml',
              'views/sale_order_inherit1.xml',
              'pivots/acme_shipping_kpi_pivot.xml',
              'pivots/acme_outsourcing_kpi_pivot.xml',
              'pivots/acme_wkorderqc_kpi_pivot.xml',
              'pivots/acme_outorderqc_kpi_pivot.xml',
              'views/acme_iot_menu.xml',

    ],
    'installable': True,
    'application': True,

}
